name:                thresholdelgamal
version:             0.1.0.0
github:              "jamidt/thresholdelgamal"
license:             BSD3
author:              "Jan Schmidt"
maintainer:          "jamidt@users.noreply.github.com"
copyright:           "2018 Jan Schmidt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jamidt/thresholdelgamal#readme>

dependencies:
- base >= 4.7 && < 5
- integer-gmp
- random

library:
  source-dirs: src

executables:
  thresholdelgamal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thresholdelgamal

tests:
  thresholdelgamal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thresholdelgamal
